void declarar(char* id);
void leer(char* id);
void escribir(char* id);
char* invertir(char* id);
char* multiplicar(char* id1, char* id2);
char* sumar(char* id1, char* id2);
char* restar(char* id1, char* id2);
char* dividir(char* id1, char* id2);
void guardar(char* id1, char* id2);
void iniciar();
void detener();
